# Generated by Django 5.1.1 on 2024-12-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='command',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
