# Generated by Django 5.1.4 on 2024-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='ussid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
