# Generated by Django 5.1.1 on 2024-12-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
