# Generated by Django 5.1.1 on 2024-12-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='img',
            field=models.FileField(upload_to='media/'),
        ),
    ]
