# Generated by Django 5.1.1 on 2024-12-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_log_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
